spring:
  application:
    name: embabel-meeting-summarizer-agent

embabel:
  models:
    defaultLlm: gemini-2.5-flash-lite

logging:
  level:
    #com.embabel: DEBUG
    org.springframework.ai: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"